info:
  title: Clevebitr的Hexo博客
  author: Clevebitr
  url: https://github.com/clevebitr/
defaults:
  avatar: /images/logo.png
colors:
  primary: #1890ff
global:
  chinese:
    enable: true
    family: Noto Sans SC
    url: https://fonts.googleapis.com/css2?family=Noto+Sans+SC:wght@400;500;700&display=swap
  busuanzi_counter:
    enable: false
    site_pv: false
    site_uv: false
home_banner:
  style: fixed
  subtitle:
    text: ['Loading...']
    hitokoto:
      api: https://v1.hitokoto.cn/
      enable: true
  social_links: 
    links:
      github: https://github.com/clevebitr/
comment:
  enable: false